baseURL = 'https://sandray-5.github.io/'
languageCode = 'en-us'
title = "Sandra's Galaxy"
theme = "PaperMod"

# é…ç½®
[params]
  # é¿å…ä¸extend_head.htmlå†²çª
  math = false
  # --- å¼ºåˆ¶ä¸»é¡µæ˜¾ç¤ºè¿™ä¸¤ä¸ªåˆ†ç±» ---
  mainSections = ["tech", "life"]
  # --- å…¶ä»–ç•Œé¢ç¾åŒ–è®¾ç½® (å¯é€‰) ---
  dateFormat = "2006-01-02" # è®¾ç½®æ—¥æœŸæ ¼å¼
  ShowReadingTime = true    # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowWordCount = true      # æ˜¾ç¤ºå­—æ•°

  # --- personnal information
  # é¦–é¡µæ˜¾ç¤ºçš„ä¸ªäººç®€ä»‹
  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "Hi, I'm Sandra. Sharing bits of tech and life. Happy you're here."

  # ç¤¾äº¤é“¾æ¥ (Social Icons)
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/SandraY-5"
  [[params.socialIcons]]
    name = "email"
    url = "https://sandray-5.github.io/about/"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  # å…³é”®ä¿®å¤ï¼šç¡®ä¿ Goldmark ä¸ä¼šè½¬ä¹‰ $ ç¬¦å·
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]

# --- å¯¼èˆªæ é…ç½® (Menu) ---
[menu]
  [[menu.main]]
    identifier = "tech"
    name = "Lab"
    url = "/tech/"
    weight = 10
  [[menu.main]]
    identifier = "life"
    name = "Life"
    url = "/life/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40


[outputs]
  home = ["HTML", "RSS", "JSON"] # å¿…é¡»åŠ ä¸Š JSONï¼Œæœç´¢åŠŸèƒ½ä¾èµ–å®ƒ