baseURL = 'https://sandray-5.github.io/'
languageCode = 'en-us'
title = "Sandra's Galaxy"
theme = "PaperMod"

# é…ç½®
[params]
  # 1. Basic setting
  env = "production"
  # é¿å…ä¸extend_head.htmlå†²çª
  math = false
  title = "Sandra's Galaxy"
  description = "Statistics & Life"
  # author = "Sandra"

  # 2. Page Function
  ShowToc = true          # æ˜¾ç¤ºç›®å½•
  TocOpen = true          # é»˜è®¤å±•å¼€ç›®å½•
  ShowCodeCopyButtons = true # æ˜¾ç¤ºä»£ç å¤åˆ¶æŒ‰é’® 
  dateFormat = "2006-01-02" # è®¾ç½®æ—¥æœŸæ ¼å¼
  ShowReadingTime = true    # æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowWordCount = true      # æ˜¾ç¤ºå­—æ•°

  # 3. Sections
  mainSections = ["tech", "life"] # å¯¹åº”contentä¸‹é¢ä¸¤ä¸ªæ–‡ä»¶å¤¹

  # 4. favicon
  [params.assets]
    favicon = "favicon.png"
    favicon16x16 = "favicon.png"
    favicon32x32 = "favicon.png"
    apple_touch_icon = "favicon.png"

  # 5. comment
  [params.comments]
    provider = "giscus"
  
  # 6. Giscus setting
  [params.giscus]
    repo = "SandraY-5/SandraY-5.github.io"
    repoID = "R_kgDOQlM_dw"
    category = "General"
    categoryID = "DIC_kwDOQlM_d84Czksp"
    mapping = "url"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "zh-CN"

  # 7. bio
  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "Hi, I'm Sandra. Sharing bits of tech and life. Happy you're here."

  # 8. social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/SandraY-5"
  [[params.socialIcons]]
    name = "email"
    url = "https://sandray-5.github.io/about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  # å…³é”®ä¿®å¤ï¼šç¡®ä¿ Goldmark ä¸ä¼šè½¬ä¹‰ $ ç¬¦å·
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
# --- End of [params] ---


# --- å¯¼èˆªæ é…ç½® (Menu) ---
[menu]
  [[menu.main]]
    identifier = "tech"
    name = "Lab"
    url = "/tech/"
    weight = 10
  [[menu.main]]
    identifier = "life"
    name = "Life"
    url = "/life/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40
  [[menu.main]]
    identifier = "archives"
    name = "Archive"  # æˆ–è€…å« "Archive"
    url = "/archives/"
    weight = 50        # æ’åœ¨ Search åé¢


[outputs]
  home = ["HTML", "RSS", "JSON"] # å¿…é¡»åŠ ä¸Š JSONï¼Œæœç´¢åŠŸèƒ½ä¾èµ–å®ƒ